version: '3'
services:
  web:
    container_name: web
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"